import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { SearchBar } from "components/SearchBar/SearchBar";
import { BlankCard } from "components/BlankCard/BlankCard";
import { StatusList } from "components/StatusList/StatusList";
import { StatusItem } from "components/StatusItem/StatusItem";
import { Map } from "components/Map/Map";
import classNames from "classnames";
const useIsBrowserEnv = () => {
  const [isBrowserEnv, setIsBrowserEnv] = useState(false);
  useEffect(() => {
    setIsBrowserEnv(true);
  }, []);

  return isBrowserEnv;
};
// https://stackoverflow.com/questions/57704196/leaflet-with-next-js
// https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/
// https://epicreact.dev/the-latest-ref-pattern-in-react/
// https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97
export default function Home() {
  const isBrowserEnv = useIsBrowserEnv();
  // useEffect(() => {
  //   if (isBrowserEnv && mapRef?.current) {
  //     const map = L.map(mapRef.current).setView([51.505, -0.09], 13);
  //     L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
  //       attribution:
  //         '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
  //     }).addTo(map);
  //   }
  // }, [isBrowserEnv]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header container">
        <h1>IP Address Tracker</h1>
        <div className="search-bar">
          <input type="search" />
          <button>{">"}</button>
        </div>
        <div className="status-card">
          <ul className="status-list">
            <li className="status-item">
              <h2 className="status-property">IP Address</h2>
              <p className="status-value">192.212.174.101</p>
            </li>
            <li className="status-item">
              <h2 className="status-property">Location</h2>
              <p className="status-value">Brooklyn, NY 10001</p>
            </li>
            <li className="status-item">
              <h2 className="status-property">Timezone</h2>
              <p className="status-value">UTC -05:00</p>
            </li>
            <li className="status-item">
              <h2 className="status-property">ISP</h2>
              <p className="status-value">SpaceX Starlink</p>
            </li>
          </ul>
        </div>
      </header>
      <main>
        <div className="map" />
      </main>
    </div>
  );
}
/* <div className="attribution">
        Challenge by{" "}
        <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
          Frontend Mentor
        </a>
        . Coded by <a href="#">Your Name Here</a>.
      </div>
    </div> */
