import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { SearchBar } from "components/SearchBar/SearchBar";
import { BlankCard } from "components/BlankCard/BlankCard";
const InfoDisplay = ({
  heading = "",
  children,
}: {
  heading: string;
  children: React.ReactNode;
}) => {
  return (
    <div>
      <h2>{heading}</h2>
      {children}
    </div>
  );
};
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>IP Address Tracker</h1>
      <SearchBar
        placeholder="Search for any IP address or domain"
        onTrigger={() => {
          console.log("Searching");
        }}
      />
      <BlankCard>
        <InfoDisplay heading="IP Address">
          <p>192.212.174.101</p>
        </InfoDisplay>
        <InfoDisplay heading="Location">
          <p>Brooklyn, NY 10001</p>
        </InfoDisplay>
        <InfoDisplay heading="Timezone">
          <p>UTC -05:00</p>
        </InfoDisplay>
        <InfoDisplay heading="ISP">
          <p>SpaceX Starlink</p>
        </InfoDisplay>
      </BlankCard>
    </div>
  );
}
/* <div className="attribution">
        Challenge by{" "}
        <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">
          Frontend Mentor
        </a>
        . Coded by <a href="#">Your Name Here</a>.
      </div>
    </div> */
